# permissions for end users to edit initializers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: kkk
    app.kubernetes.io/managed-by: kustomize
  name: initializer-editor-role
rules:
- apiGroups:
  - storage.kubesphere.io
  resources:
  - initializers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - storage.kubesphere.io
  resources:
  - initializers/status
  verbs:
  - get
