apiVersion: storage.kubesphere.io/v1alpha1
kind: Initializer
metadata:
  labels:
    app.kubernetes.io/name: initializer-sample
    app.kubernetes.io/managed-by: kustomize
  name: initializer-sample
spec:
  enabled: true
  initContainers:
  - name: busybox-chmod
    image: busybox:latest
    command:
      - sh
      - '-c'
      - chmod -R 777 $PVC_1_MOUNT_PATH
    resources:
      limits:
        cpu: 500m
        memory: 100Mi
      requests:
        cpu: 100m
        memory: 100Mi
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    imagePullPolicy: IfNotPresent
  - name: busybox-chown
    image: busybox:latest
    command:
      - sh
      - '-c'
      - chown -R 1001:0 $PVC_1_MOUNT_PATH
    resources:
      limits:
        cpu: 500m
        memory: 100Mi
      requests:
        cpu: 100m
        memory: 100Mi
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    imagePullPolicy: IfNotPresent
  pvcMatchers:
  - name: local-1
    pvc:
      fieldSelector:
        - key: name
          operator: In
          values:
            - ttt-mongodb-test-0
            - mongodb-mongodb-test-0
    pod:
      labelSelector:
        - key: app
          operator: In
          values:
            - mongodb-test
    storageClass:
      fieldSelector:
        - key: name
          operator: In
          values:
            - local-path
    namespace:
      labelSelector:
        - key: "kubernetes.io/metadata.name"
          operator: In
          values:
            - default
            - test
    workspace:
      fieldSelector:
        - key: name
          operator: NotIn
          values:
            - ws1
  - name: local-2
    storageClass:
      fieldSelector:
        - key: name
          operator: In
          values:
            - local-path2
  pvcInitializers:
  - pvcMatcherName: local-1
    initContainerName: busybox-chmod
  - pvcMatcherName: local-2
    initContainerName: busybox-chown
    mountPathRoot: "/pvc"
status: {}
